spring:
  application:
    name: BookingStorageService

  datasource:
    url: jdbc:postgresql://localhost:5435/root
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  server:
    port: 8080